---
title: "Big Grid Database"
author: "Andrew Crosby"
date: '`r format(Sys.time(), "%d %B, %Y")`'
output: html_document
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

knitr::opts_knit$set(root.dir = normalizePath(".."))  #Sets the working directory to the project folder
```


```{r}

rm(list=ls(all=TRUE)) 
gc()

library(tidyr)
library(stringr)
library(data.table)
library(lubridate)
library(maptools)
library(dplyr)
library(sqldf)
library(reshape2)

```


```{r}

load("0_data/processed/big-grid-veg-point.Rdata")
load("0_data/processed/big-grid-point-data.Rdata")
load("0_data/processed/big-grid-veghf-grids.Rdata")


veghf_150_2016 <- read.csv(file = "0_data/raw/10_vegHF150mscale_2016_stationgridassignment.csv", header = TRUE)
veghf_150_2017 <- read.csv(file = "0_data/raw/10_vegHF150mscale_2017_stationgridassignment.csv", header = TRUE)


veghf_300_2016 <- read.csv(file = "0_data/raw/10_vegHF36000m2scale_2016_stationgridassignment.csv", header = TRUE)
veghf_300_2017 <- read.csv(file = "0_data/raw/10_vegHF36000m2scale_2017_stationgridassignment.csv", header = TRUE)




gridnum <- sqldf("SELECT b.StationKey, b.Gridnum, a.g2x2, a.g3x3, a.g4x4, a.g5x5 FROM veghf_300_2016 a JOIN bg_ss_veg b ON a.SS = b.SS")

gridID <- data.frame(gridnum$StationKey, gridnum$Gridnum, t(sapply(1:nrow(gridnum), function(x){sapply(3:6, function(j) paste0(gridnum$Gridnum[x], "-", gridnum[x, j]))})))
colnames(gridID) <- colnames(gridnum)

statnum <- data.frame(ss = gridnum$StationKey, grid = gridnum$Gridnum, point = sapply(1:nrow(gridnum), function(x) as.numeric(substr(gridnum$StationKey[x], 9, 11))))



```


```{r}

point_hf <- veghf_300[, c("prop.softlin", "prop.softpoly", "prop.hardlin", "prop.hardpoly")]

grids_hf <- lapply(1:length(grids_veghf), function(x) grids_veghf[[x]][, c("prop.softlin", "prop.softpoly", "prop.hardlin", "prop.hardpoly")])

apply(point_hf, 2, mean)
apply(apply(point_hf, 2, range), 2, sum)

within_block_hetero <- do.call(rbind, lapply(1:length(grids_hf), function(i) apply(do.call(rbind, lapply(1:nlevels(as.factor(gridID[, (i + 2)])), function(x){
  apply(apply(point_hf[which(gridID[, (i + 2)] == levels(as.factor(gridID[, (i + 2)]))[x]), ], 2, range), 2, sum)
})),2, mean)))

among_block_hetero <- do.call(rbind, lapply(1:length(grids_hf), function(x) apply(apply(grids_hf[[x]], 2, range), 2, sum)))

png(filename = "3_outputs/figures/heterogeneity.png",
    width = 1800, height = 1800, units = "px", pointsize = 0.5,
    bg = "white", res = 300)
par(mfrow=c(2, 1))
boxplot(t(within_block_hetero))
boxplot(t(among_block_hetero))
dev.off()

```

Re-do the human footprint data with categories that make more sense. 
```{r}


hf <- veghf_300_2017[, 86:112]

colSums(hf)/1000^2

sum.point <- function(vars, veg_ss, rad, name){
p <- list()
for(i in 1:length(vars)){
  r <- list()
  t <- vars[i] 
  s <- 1
  for(j in 1:ncol(veg_ss)){
    c <- colnames(veg_ss)[j] 
    if(substr(c, 1, nchar(t)) == vars[i]){
      r[[(s)]] <- j
    }else{
      next
    }
    s <- s + 1
  }
  p[[i]] <- r
}

mat <- matrix(0, nrow(veg_ss), length(vars))
for(i in 1:ncol(mat)){
  d <- as.matrix(veg_ss[, unlist(p[[i]])])
  if(ncol(d) == 1){
    mat[, i] <- d/rad
  }else{
    mat[, i] <- rowSums(d)/rad
  }
}
colnames(mat) <- vars
rownames(mat) <- veg_ss$StationKey

prop <- as.matrix(rowSums(mat))
rownames(prop) <- veg_ss$StationKey
colnames(prop) <- paste0("prop.", name)

return(prop)

}


sum.point.scale <- function(varlist, veg_hf, ss, rad, namelist){
  
  veg_ss <- sqldf("SELECT b.StationKey, a.* FROM veg_hf a JOIN ss b ON a.SS = b.SS")

  d.var <- list()
  for(i in 1:length(varlist)){
    d.var[[i]] <- sum.point(varlist[[i]], veg_ss, rad, namelist[[i]])
    
  }
  t <- as.data.frame(do.call(cbind, d.var)) 
  t$total.hf <- rowSums(t)
  t.1 <- t
  for(i in 1:nrow(t)){
    for(j in 1:ncol(t)){
      t.1[i, j] <- ifelse(t[i, j] > 1, 1, t[i, j])
    }
  }  
  return(t.1)
}


seismic <- c("SeismicLineWide", "SeismicLineNarrow")
widelin <- c("Pipeline", "TransmissionLine", "RoadTrailVegetated", "RoadVegetatedVerge", "RailVegetatedVerge", "RoadHardSurface", "RailHardSurface")
wells <- c("WellSite")
industry <- c("IndustrialSiteRural", "MineSite", "BorrowpitsDugoutsSumps", "OtherDisturbedVegetation")


hf150_2016_2 <- sum.point.scale(varlist = list(seismic, widelin, wells, industry), veg_hf = veghf_150_2016, ss = bg_ss_veg, rad = pi*150^2, namelist = c("seismic", "widelin", "wells", "industry"))
hf150_2017_2 <- sum.point.scale(varlist = list(seismic, widelin, wells, industry), veg_hf = veghf_150_2017, ss = bg_ss_veg, rad = pi*150^2, namelist = c("seismic", "widelin", "wells", "industry"))



hf300_2016_2 <- sum.point.scale(varlist = list(seismic, widelin, wells, industry), veg_hf = veghf_300_2016, ss = bg_ss_veg, rad = 600^2, namelist = c("seismic", "widelin", "wells", "industry"))
head(hf300_2016_2)

hf300_2017_2 <- sum.point.scale(varlist = list(seismic, widelin, wells, industry), veg_hf = veghf_300_2017, ss = bg_ss_veg, rad = 600^2, namelist = c("seismic", "widelin", "wells", "industry"))
head(hf300_2016_2)


save(hf150_2016_2, hf150_2017_2, hf300_2016_2, hf300_2017_2, file = "0_data/processed/big-grid-hf-point_2.Rdata")


```


Put it together into an analysis package 
```{r}

# Get the ovenbird data to use in matching vegetation years to survey years
oven_point <- bg_pa[, c(1:2, which(colnames(bg_pa) =="OVEN"))]

oven_pt <- oven_point %>% spread(survey, OVEN)
oven_pt <- oven_pt[match(bg_nsurv_veg$StationKey, oven_pt$StationKey), 1:5]
head(oven_pt)
all.equal(oven_pt$StationKey, bg_nsurv_veg$StationKey)


# Get the year in which each survey was done
data.year <- sqldf::sqldf("SELECT DISTINCT StationKey, Year FROM bg_maxyear_veg;")
data.year <- data.year[match(oven_pt$StationKey, data.year$StationKey), ]
all.equal(data.year$StationKey, oven_pt$StationKey)


# Write the function to match the veg  and hf data to the survey years
veg_year <- function(i, v2016, v2017, hf2016, hf2017){
  if(data.year$Year[i] <= 2016){
    v <- data.frame(c(v2016[which(rownames(v2016) == data.year$StationKey[i]), ], hf2016[which(rownames(hf2016) == data.year$StationKey[i]), ]))
  }else{
    v <- data.frame(c(v2017[which(rownames(v2017) == data.year$StationKey[i]), ], hf2017[which(rownames(hf2017) == data.year$StationKey[i]), ]))
  }
  return(unlist(v))
}

veg_year(1, veg_300_2016, veg_300_2017, hf300_2016_2, hf300_2017_2)

# Make the 300 meter dataset
veghf_300_2 <- data.frame(t(sapply(1:nrow(data.year), veg_year, v2016 = veg_300_2016, v2017 = veg_300_2017, hf2016 = hf300_2016_2, hf2017 = hf300_2017_2)))
rownames(veghf_300_2) <- data.year$StationKey
all.equal(rownames(veghf_300_2), oven_pt$StationKey)


veghf_150_2 <- data.frame(t(sapply(1:nrow(data.year), veg_year, v2016 = veg_150_2016, v2017 = veg_150_2017, hf2016 = hf150_2016_2, hf2017 = hf150_2017_2)))
rownames(veghf_150_2) <- data.year$StationKey
all.equal(rownames(veghf_150_2), oven_pt$StationKey)



# Get the survey variables and put into a site x survey x variable array
det.var.raw <- data.frame(bg_maxyear_veg[, c("StationKey", "survey")], int = rep(1, nrow(bg_maxyear_veg)), jday = scale(bg_maxyear_veg$julian), tssr = scale(bg_maxyear_veg$tssr), jday2 = scale(bg_maxyear_veg$julian^2))

det.var.scale <- det.var.raw[-which(det.var.raw$survey > 4), ]

det.var.m <- reshape2::melt(det.var.scale, id = c("StationKey", "survey"))

det.var_veg<- acast(det.var.m, StationKey ~ survey ~ variable)
det.var_veg <- det.var_veg[match(bg_nsurv_veg$StationKey, rownames(det.var_veg)), , ]
all.equal(rownames(det.var_veg), bg_nsurv_veg$StationKey, oven_pt$StationKey, rownames(veghf_300))

all.equal(data.year$StationKey, rownames(det.var_veg))



save(bg_count_veg, bg_maxyear_veg, bg_nsurv_veg, bg_pa, bg_ss_veg, data.year, veghf_300_2, veghf_150_2, det.var_veg, file = "0_data/processed/big-grid-point-data_2.Rdata")



```


Check to see if models come out as expected
```{r}

oven_count <- bg_count_veg[, c(1,2, which(colnames(bg_count_veg) == "OVEN"))]

oven_ct <- oven_count %>% spread(survey, OVEN)
oven_ct <- oven_ct[match(bg_nsurv_veg$StationKey, oven_ct$StationKey), 1:5]
head(oven_ct)
all.equal(oven_ct$StationKey, bg_nsurv_veg$StationKey)


oven.try <- apply(oven_ct[, -1], 1, max, na.rm = TRUE)

summary(glm(oven.try ~ 1, family = "poisson"))
summary(glm(oven.try ~ veghf_300_2$prop.decid, family = "poisson"))
summary(glm(oven.try ~ veghf_300_2$wt_mean_age + veghf_300_2$prop.decid, family = "poisson"))

oven.try2 <- apply(oven_pt[, -1], 1, max, na.rm = TRUE)
summary(glm(oven.try2 ~ 1, family = "binomial"))
summary(glm(oven.try2 ~ veghf_300_2$prop.decid, family = "binomial"))
summary(glm(oven.try2 ~ veghf_300_2$wt_mean_age + veghf_300_2$prop.decid, family = "binomial"))
summary(glm(oven.try2 ~ veghf_300_2$wt_mean_age + veghf_300_2$prop.decid + veghf_300_2$total.hf, family = "binomial"))

cawa_point <- bg_pa[, c(1:2, which(colnames(bg_pa) =="CAWA"))]

cawa_pt <- cawa_point %>% spread(survey, CAWA)
cawa_pt <- cawa_pt[match(bg_nsurv_veg$StationKey, cawa_pt$StationKey), 1:5]
cawa.try <- apply(cawa_pt[, -1], 1, max, na.rm = TRUE)
summary(glm(cawa.try ~ 1, family = "binomial"))
summary(glm(cawa.try ~ veghf_300$prop.decid, family = "binomial"))
summary(glm(cawa.try ~ veghf_300$wt_mean_age + veghf_300$prop.decid, family = "binomial"))
summary(glm(cawa.try ~ veghf_300$wt_mean_age + veghf_300$prop.decid + veghf_300$total.hf, family = "binomial"))

```




Summarize at different scales 
```{r}

gridnum <- sqldf("SELECT b.StationKey, b.Gridnum, a.g2x2, a.g3x3, a.g4x4, a.g5x5 FROM veghf_300_2016 a JOIN bg_ss_veg b ON a.SS = b.SS")

gridID <- data.frame(gridnum$StationKey, gridnum$Gridnum, t(sapply(1:nrow(gridnum), function(x){sapply(3:6, function(j) paste0(gridnum$Gridnum[x], "-", gridnum[x, j]))})))
colnames(gridID) <- colnames(gridnum)

veg_hf_sum <- function(veg_origin, veg, hf, ss, gridID, rad, gridsize){
  veg_ss<- sqldf("SELECT b.StationKey, a.* FROM veg_origin a JOIN ss b ON a.SS = b.SS")
  
  veg_ss <- veg_ss[, 1:which(colnames(veg_ss) == "CCSpruce4")]
  all.equal(veg_ss$StationKey, gridID$StationKey, rownames(veg))
  
  
  
  age <- c(4.5, 10, 20, 40, 60, 80, 100, 120, 140, 160) 
  age.des <- c("R", 1:9) 
  
  p <- list() 
  for(i in 1:length(age.des)){ 
    t <- list() 
    s <- 1 
    for(j in 1:ncol(veg_ss)){
 
      c <- colnames(veg_ss)[j] 
      if(substr(c, nchar(c), nchar(c)) == age.des[i]){
        t[[(s)]] <- j
        }else{
          next
          } 
      s <- s + 1 
      } 
    p[[i]] <- t 
  }
  
  age.mat <- data.frame(matrix(0, nrow(veg_ss), length(age)))
  for(i in 1:ncol(age.mat)){
    age.mat[, i] <- rowSums(veg_ss[, unlist(p[[i]])])
    }
  colnames(age.mat) <- age.des
  rownames(age.mat) <- veg_ss$StationKey
  
  gridlist <- list()
  for(i in 3:ncol(gridID)){
    # Sum land cover types in grid 
    d <- ((veg[-1]*rad) %>% group_by(gridID[, i]) %>% summarize_at(colnames(veg[-1]), list(sum = sum)))
    
    colnames(d)[-1] <- substr(colnames(d)[-1], 1, nchar(colnames(d)[-1]) - 4) # Remove "_sum" from column names
    
    n <- which(sapply(1:nrow(d), function(x) if_else(substr(d$`gridID[, i]`[x], nchar(d$`gridID[, i]`[x]) - 1, nchar(d$`gridID[, i]`[x])) == "-0", 0, 1)) == 1)
    d.2 <- d[n, ]
    
    age.gr <- ((age.mat) %>% group_by(gridID[, i]) %>% summarize_at(colnames(age.mat), list(sum = sum)))[, -1]/d$total.for
    age.grid <- age.gr[n, ]
    wt_mean_age <- as.matrix(age.grid) %*% age
    rownames(wt_mean_age) <- d.2$`gridID[, i]`
    colnames(wt_mean_age) <- "wt_mean_age"
    
    d.3 <- data.frame(wt_mean_age, d.2[, -1]/(rad*gridsize[i-2]))
    
    d.4 <- ((hf*rad) %>% group_by(gridID[, i]) %>% summarize_at(colnames(hf), list(sum = sum)))
    colnames(d.4)[-1] <- substr(colnames(d.4)[-1], 1, nchar(colnames(d.4)[-1]) - 4) # Remove "_sum" from column names
    d.4.1 <- d.4[n, ][, -1]/(rad*gridsize[i-2])
    rownames(d.4.1) <- d.4$`gridID[, i]`[n]
    
    t <- data.frame(gridID = d.2$`gridID[, i]`) 
    t1 <- data.frame(gID = gridID[, i], gnum = gridID[, 2])
    gnum <-  sqldf("SELECT DISTINCT a.gridID, b.gnum FROM t a JOIN t1 b ON a.gridID = b.gID")
    
    gridlist[[i - 2]] <- cbind(gnum, d.3, d.4.1)
    ifelse(all.equal(rownames(d.3), gnum$gridID, rownames(d.4.1), gridlist[[i - 2]]$gridID), next, break)

  } 
  return(gridlist)
}

veg_origin <- veghf_300_2016
veg = veg_300_2016
rad = 600^2

hf = hf300_2016
ss = bg_ss
gridsize = c(4, 9, 16, 25)



grids2016_2 <- veg_hf_sum(veg_origin = veghf_300_2016, veg = veg_300_2016, hf = hf300_2016_2, gridID = gridID, rad = 600^2, ss = bg_ss_veg, gridsize = c(4, 9, 16, 25))
grids2017_2 <- veg_hf_sum(veg_origin = veghf_300_2017, veg = veg_300_2017, hf = hf300_2017_2, gridID = gridID, rad = 600^2, ss = bg_ss_veg, gridsize = c(4, 9, 16, 25))




```




```{r}

grid_year <- sqldf("SELECT DISTINCT b.Gridnum, MAX(a.Year) grid_year FROM bg_maxyear_veg a JOIN gridnum b ON a.StationKey = b.StationKey GROUP BY Gridnum")
head(grid_year)
length(which(grid_year$`COUNT(Year)` > 1))

a <- grids2016_2
b <- grids2017_2

gridsize = c(4, 9, 16, 25)

grids_veghf_2 <- list()
for(i in 1:length(gridsize)){
  d <- a[[i]]$gnum
  e <- do.call(rbind, lapply(1:length(d), function(x) if(grid_year[which(grid_year$Gridnum == d[x]), "grid_year"] <= 2016){a[[i]][x, ]}else{b[[i]][x, ]}))
  grids_veghf_2[[i]] <- e
}


save(grids2016_2, grids2017_2, grids_veghf_2, gridID, file = "0_data/processed/big-grid-veghf-grids_2.Rdata")

```











